// <auto-generated/>
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

namespace Microsoft.Toolkit.Wpf.UI.XamlHost
{
    /// <summary>
    /// Defines assembly visibility for <seealso cref="WindowsXamlHost"/>
    /// </summary>
    public partial class WindowsXamlHost
    {
    }
}
