// Copyright (c) Richasy. All rights reserved.

namespace Richasy.Bili.Models.Enums
{
    /// <summary>
    /// Localized text resource name.
    /// </summary>
    public enum LanguageNames
    {
#pragma warning disable SA1602 // Enumeration items should be documented
        AppName,
        AppDescription,
        Confirm,
        Cancel,
        Navigation,
        Popular,
        Rank,
        Partition,
        SpecialColumn,
        Live,
        Personal,
        DynamicFeed,
        MyFavorite,
        SeeLater,
        ViewHistory,
        HelpAndSupport,
        PartitionLoading,
        Recommend,
        TenThousands,
        Billion,
        Hours,
        Minutes,
        Seconds,
        ComprehensiveDynamics,
        SelectSortType,
        SortByDefault,
        SortByNewest,
        SortByPlay,
        SortByReply,
        SortByDanmaku,
        SortByFavorite,
        SearchTip,
        SearchTipSlim,
        SignInTitle,
        UserName,
        Password,
        SignIn,
        UserNameHolder,
        PasswordHolder,
        Captcha,
        CaptchaHolder,
        ValidUserNameOrPasswordTip,
        CaptchaIsEmpty,
        InputCaptchaTip,
        InvalidUserNameOrPassword,
        NeedQRLogin,
        PasswordLoginTip,
        QRLoginTip,
        SwitchToPasswordLogin,
        SwitchToQRLogin,
        Refresh,
        FailedToLoadQRCode,
        QRCodeExpired,
        LoginFailed,
        PleaseSignIn,
        Topic,
        ForeignAnime,
        DomesticAnime,
        Documentary,
        Movie,
        TV,
        SignOut,
        MyWebPage,
        Message,
        WholePartitions,
        Original,
        Rookie,
        Score,
        RankRequestFailed,
        PartitionRequestFailed,
        RequestRecommendFailed,
        RequestSubPartitionFailed,
        RequestPopularFailed,
#pragma warning restore SA1602 // Enumeration items should be documented
    }
}
