// Copyright (c) Richasy. All rights reserved.

namespace Richasy.Bili.Models.Enums
{
    /// <summary>
    /// Application settings key.
    /// </summary>
    public enum SettingNames
    {
#pragma warning disable SA1602 // Enumeration items should be documented
        AppTheme,
        BiliUserId,
        AuthorizeResult,
        IsPrelaunch,
        IsStartup,
        IsAutoPlayWhenLoaded,
        DefaultPlayerDisplayMode,
        IsPreferHighQuality,
        PreferCodec,
        SingleFastForwardAndRewindSpan,
        DefaultMTCControlMode,
        DefaultVideoFormat,
        IsShowDanmaku,
        DanmakuOpacity,
        DanmakuFontSize,
        DanmakuDensity,
        DanmakuFont,
        IsDanmakuMerge,
        UseCloudShieldSettings,
        DanmakuStyle,
        IsDanmakuBold,
        Volume,
        IsDanmakuStandardSize,
        DanmakuLocation,
        DanmakuColor,
        DoubleClickBehavior,
        IsShowDanmakuBar,
        CanShowSubtitle,
        PlaybackRate,
        DanmakuArea,
        DanmakuSpeed,
        DisableP2PCdn,
        IsContinusPlay,
        IgnoreVersion,
        IsOnlyShowIndex,
        CanContinuePlay,
        ContinuePlayTitle,
        SupportContinuePlay,
        Download_UseMp4Box,
        Download_OnlyHevc,
        Download_OnlyAvc,
        Download_OnlyAudio,
        Download_OnlyVideo,
        Download_OnlySubtitle,
        Download_UseMultiThread,
        Download_UseAppInterface,
        Download_UseTvInterface,
        Download_UseInternationalInterface,
        Download_DownloadDanmaku,
        Download_DownloadFolder,
        Download_UsePartPerfix,
        Download_UseQualitySuffix,
        Download_UseInteractionQuality,
        CanSaveScreenshot,
        OpenScreenshotAfterSave,
        CopyScreenshotAfterSave,
        PlaybackRateEnhancement,
        GlobalPlaybackRate,
        IsFirstClickTag,
        IsAutoPlayNextRelatedVideo,
        IsLiveAudioOnly,
        IsDanmakuLimit,
#pragma warning disable SA1602 // Enumeration items should be documented
    }
}
