name: Bug 报告
description: 提交 Bug 以帮助我们提高应用体验
title: "[Bug] 我的标题"
assignees: Richasy
labels:
  - "bug 🐛"
body:
- type: markdown
  attributes: 
    value: |
      ## 写在开头
      🚨 请务必完整填写下面的内容，如果缺少必要的信息，开发者可能会在未调查的情况下直接关闭问题 🚨
      
- type: textarea
  id: description
  validations:
    required: true
  attributes:
     label: Bug 描述
     description: 请简短的描述你遇到的问题
- type: textarea
  id: repro-steps
  validations:
    required: true
  attributes:
     label: 复现问题的步骤
     render: plain text
     description: 请提供复现问题的步骤，如果不能，请写明原因
     placeholder: |
        干净清晰的复现步骤有助于开发者更快定位问题所在，你所遇到的问题也会获得更高的优先级.

        示例步骤:
        1. 打开应用
        2. 进入 '...'
        3. 点击 '....'
        4. 滚动至 '....'
        5. 发现问题
- type: textarea
  id: expected-behavior
  validations:
    required: true
  attributes:
     label: 预期行为
     description: 简要描述你希望看到什么样的结果
- type: textarea
  id: screenshots
  attributes:
     label: 截图
     description: 如果可以，提交截图更有助于我们分析问题
- type: checkboxes
  id: environment-package-source
  attributes:
     label: 应用来源
     description: 你是从哪里下载的哔哩呢？
     options:
       - label: Microsoft Store
       - label: Github
       - label: 其它
- type: input
  id: environment-package-other-source
  attributes:
     label: 其它来源
     description: 如果你是从其它地方下载的哔哩，请注明来源
- type: checkboxes
  id: environment-app-target-version
  attributes:
     label: 系统版本
     description: 选择一个你发现问题的系统版本
     options:
       - label: Windows 10 1809 (Build 17763)
       - label: Windows 10 1903 (Build 18362)
       - label: Windows 10 1909 (Build 18363)
       - label: Windows 10 2004 (Build 19041)
       - label: Windows 10 20H2 (Build 19042)
       - label: Windows 10 21H1 (Build 19043)
       - label: Windows 11 21H2 (Build 22000)
       - label: 其它 (需注明)
- type: input
  id: environment-app-target-other-version
  attributes:
     label: 其它系统版本
     description: 如果你是在特别的系统版本中运行应用，请注明系统版本
- type: dropdown
  id: form-factor
  attributes: 
     multiple: true
     label: 运行设备
     description: 选择你当前运行哔哩的设备类型
     options:
       - 桌面/台式机
       - 桌面/平板或笔记本
       - Xbox
       - ARM64 设备
- type: textarea
  id: log-info
  attributes:
     label: 日志记录
     description: 请在应用设置中打开 日志记录 面板，打开日志文件夹，选取问题发生当日的日志记录作为 Issue 的附件上传
- type: textarea
  id: additional-context
  attributes:
     label: 备注
     description: 添加你认为有必要的信息

- type: dropdown
  id: contribution
  attributes:
     label: 人人为我，我为人人
     description: 哔哩变得更好，我们所有参与者都将受益，如果可以的话，你是否愿意帮忙解决这个问题？
     options:
       - 是的，我希望我的代码出现在哔哩中
       - 我更擅长发现问题