name: 功能需求
description: 给项目提供建议或点子
title: "需求标题"
labels: [feature]
body:
  - type: markdown
    attributes:
      value: |
        🚨 请务必完整填写下面的内容，如果缺少必要的信息，开发者可能会在未调查的情况下直接关闭问题  🚨
  - type: textarea
    validations:
      required: false
    attributes:
      label: 想要解决的问题或者功能的使用场景
      description: |
        请描述你遇到的问题或者链接到已存在的 issue.
        从用户故事（User Story）开始，简明扼要的说明该功能的适用场景。
        说明当前应用在没有该功能情况下对你造成了哪些困扰，而有了这项功能后又能为用户创造怎样的价值。
      placeholder: 描述你想要解决的问题或者功能的使用场景
  - type: textarea
    validations:
      required: true
    attributes:
      label: 解决方案
      desciption: 描述你所预期的解决方案，它会以怎样的方式解决你所遇到的问题
  - type: textarea
    validations:
      required: true
    attributes:
      label: 可能的替代方案
      desciption: 当前一种解决方案难以实现时，你是否考虑了其他的替代方案？是否有一个最低的，可接受的实现目标？
  - type: textarea
    attributes:
      label: 备注和截图
      desciption: 添加一些你认为有必要的备注信息，或者展示一些能表现你思路的草图