// <auto-generated/>
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

namespace Microsoft.Toolkit.Win32.UI.XamlHost
{
    /// <summary>
    /// Defines assembly visibility for <seealso cref="IDesktopWindowXamlSourceNative"/>
    /// </summary>
    public partial interface IDesktopWindowXamlSourceNative
    {
    }

    /// <summary>
    /// Defines assembly visibility for <seealso cref="DesktopWindowXamlSourceExtensions"/>
    /// </summary>
    public static partial class DesktopWindowXamlSourceExtensions
    {
    }
}
